# Checkpoint Two: Exploratory Data Analysis

Now that your chosen dataset is approved, it is time to start working on your analysis. Use this notebook to perform your EDA and make notes where directed to as you work.

## Getting Started

Since we have not provided your dataset for you, you will need to load the necessary files in this repository. Make sure to include a link back to the original dataset here as well.

My dataset:

Your first task in EDA is to import necessary libraries and create a dataframe(s). Make note in the form of code comments of what your thought process is as you work on this setup task.

In [1]:
import pandas as pd
import numpy as np

pfw_public = pd.read_csv('C:/Users/Erin/LaunchCode/git_hub/data-analysis-projects/the-final-project/PFW_2021_public.csv')
pfw_count_site = pd.read_csv('C:/Users/Erin/LaunchCode/git_hub/data-analysis-projects/the-final-project/PFW_count_site_data_public_2021.csv')
#imported the two .csv files I will be using

In [2]:
pfw = pd.merge(pfw_count_site, pfw_public, on='loc_id', how='left')
#created a merged dataframe on the 'loc_id' column 
display(pfw)

,loc_id,proj_period_id,yard_type_pavement,yard_type_garden,yard_type_landsca,yard_type_woods,yard_type_desert,hab_dcid_woods,hab_evgr_woods,hab_mixed_woods,...,how_many,valid,reviewed,day1_am,day1_pm,day2_am,day2_pm,effort_hrs_atleast,snow_dep_atleast,Data_Entry_Method
0,L100016,PFW_2002,0.0,0.0,1.0,0.0,0.0,1.0,NaN,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,L100016,PFW_2003,0.0,0.0,1.0,0.0,0.0,1.0,NaN,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,L100016,PFW_2004,0.0,0.0,1.0,0.0,0.0,1.0,NaN,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,L100016,PFW_2005,0.0,0.0,1.0,0.0,0.0,1.0,NaN,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,L100016,PFW_2006,0.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
693588,L999923,PFW_2010,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
693589,L99994,PFW_2002,0.0,0.0,1.0,0.0,0.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
693590,L99996,PFW_2002,0.0,0.0,1.0,1.0,0.0,1.0,NaN,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
693591,L9999665,PFW_2020,0.0,0.0,1.0,1.0,0.0,0.0,0.0,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
693592,L99999,PFW_2002,0.0,0.0,1.0,1.0,0.0,NaN,1.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

## Get to Know the Numbers

Now that you have everything setup, put any code that you use to get to know the dataframe and its rows and columns better in the cell below. You can use whatever techniques you like, except for visualizations. You will put those in a separate section.

When working on your code, make sure to leave comments so that your mentors can understand your thought process.

In [3]:
# I also need to know what the species code means
# The "species_code" column was too abstract to be useful to work with. I brought in a table from PFW that lists the American English name and joined on 'species_code'.
# I then added a new column for 'american_english_name' and dropped the s'species_code' column. 
pfw_species = pd.read_csv('C:/Users/Erin/LaunchCode/git_hub/data-analysis-projects/the-final-project/pfw_species_codes_dict.csv')
pfw = pd.merge(pfw, pfw_species, on='species_code', how='inner')
display(pfw)

,loc_id,proj_period_id,yard_type_pavement,yard_type_garden,yard_type_landsca,yard_type_woods,yard_type_desert,hab_dcid_woods,hab_evgr_woods,hab_mixed_woods,...,day2_pm,effort_hrs_atleast,snow_dep_atleast,Data_Entry_Method,alt_full_spp_code,n_locations,scientific_name,american_english_name,taxonomy_version,taxonomic_sort_order
0,L100032,PFW_2002,0.0,0.0,1.0,1.0,0.0,1.0,NaN,NaN,...,1.0,1.001,0.000,PFW Web 4.1.4,NaN,85183,Junco hyemalis,Dark-eyed Junco,2022,32449
1,L100032,PFW_2002,0.0,0.0,1.0,1.0,0.0,1.0,NaN,NaN,...,1.0,1.001,0.001,PFW Web 4.0.4,NaN,40529,Zonotrichia albicollis,White-throated Sparrow,2022,32526
2,L100032,PFW_2002,0.0,0.0,1.0,1.0,0.0,1.0,NaN,NaN,...,1.0,1.001,5.000,PFW Web 4.1.4,NaN,73537,Cyanocitta cristata,Blue Jay,2022,20786
3,L100032,PFW_2002,0.0,0.0,1.0,1.0,0.0,1.0,NaN,NaN,...,1.0,1.001,0.000,PFW Web 4.1.4,NaN,73537,Cyanocitta cristata,Blue Jay,2022,20786
4,L100032,PFW_2002,0.0,0.0,1.0,1.0,0.0,1.0,NaN,NaN,...,1.0,1.001,15.001,PFW Web 4.1.4,NaN,73537,Cyanocitta cristata,Blue Jay,2022,20786
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
504980,L9994340,PFW_2021,0.0,0.0,1.0,1.0,0.0,0.0,0.0,1.0,...,1.0,0.001,0.000,PFW Web 4.1.4,NaN,63870,Passer domesticus,House Sparrow,2022,30886
504981,L9994340,PFW_2021,0.0,0.0,1.0,1.0,0.0,0.0,0.0,1.0,...,1.0,0.001,0.000,PFW Web 4.1.4,NaN,67264,Poecile atricapillus,Black-capped Chickadee,2022,21563
504982,L9994340,PFW_2021,0.0,0.0,1.0,1.0,0.0,0.0,0.0,1.0,...,1.0,1.001,5.000,PFW Web 4.1.4,NaN,9993,Pipilo maculatus,Spotted Towhee,2022,32713
504983,L9994340,PFW_2021,0.0,0.0,1.0,1.0,0.0,0.0,0.0,1.0,...,1.0,1.001,0.000,PFW Web 4.1.4,NaN,1500,Aphelocoma woodhouseii,Woodhouse's Scrub-Jay,2022,20805
504984,L9994340,PFW_2021,0.0,0.0,1.0,1.0,0.0,0.0,0.0,1.0,...,1.0,1.001,5.000,PFW Web 4.1.4,NaN,63870,Passer domesticus,House Sparrow,2022,30886

In [4]:
pfw.columns
#getting a sense of what columns I am working with

Index(['loc_id', 'proj_period_id', 'yard_type_pavement', 'yard_type_garden',
       'yard_type_landsca', 'yard_type_woods', 'yard_type_desert',
       'hab_dcid_woods', 'hab_evgr_woods', 'hab_mixed_woods', 'hab_orchard',
       'hab_park', 'hab_water_fresh', 'hab_water_salt', 'hab_residential',
       'hab_industrial', 'hab_agricultural', 'hab_desert_scrub',
       'hab_young_woods', 'hab_swamp', 'hab_marsh', 'evgr_trees_atleast',
       'evgr_shrbs_atleast', 'dcid_trees_atleast', 'dcid_shrbs_atleast',
       'fru_trees_atleast', 'cacti_atleast', 'brsh_piles_atleast',
       'water_srcs_atleast', 'bird_baths_atleast', 'nearby_feeders',
       'squirrels', 'cats', 'dogs', 'humans', 'housing_density',
       'fed_yr_round', 'fed_in_jan', 'fed_in_feb', 'fed_in_mar', 'fed_in_apr',
       'fed_in_may', 'fed_in_jun', 'fed_in_jul', 'fed_in_aug', 'fed_in_sep',
       'fed_in_oct', 'fed_in_nov', 'fed_in_dec', 'numfeeders_suet',
       'numfeeders_ground', 'numfeeders_hanging', 'numfeeders_platfrm',
       'numfeeders_humming', 'numfeeders_water', 'numfeeders_thistle',
       'numfeeders_fruit', 'numfeeders_hopper', 'numfeeders_tube',
       'numfeeders_other', 'population_atleast',
       'count_area_size_sq_m_atleast', 'latitude', 'longitude',
       'subnational1_code', 'entry_technique', 'sub_id', 'obs_id', 'Month',
       'Day', 'Year', 'PROJ_PERIOD_ID', 'species_code', 'how_many', 'valid',
       'reviewed', 'day1_am', 'day1_pm', 'day2_am', 'day2_pm',
       'effort_hrs_atleast', 'snow_dep_atleast', 'Data_Entry_Method',
       'alt_full_spp_code', 'n_locations', 'scientific_name',
       'american_english_name', 'taxonomy_version', 'taxonomic_sort_order'],
      dtype='object')

In [5]:
pfw.shape
#getting a sense of the shape of the data. I have 89 columns and over 500,000 rows, which is almost certainly too much for my purposes.

(504985, 89)

In [6]:
pfw.head()

,loc_id,proj_period_id,yard_type_pavement,yard_type_garden,yard_type_landsca,yard_type_woods,yard_type_desert,hab_dcid_woods,hab_evgr_woods,hab_mixed_woods,...,day2_pm,effort_hrs_atleast,snow_dep_atleast,Data_Entry_Method,alt_full_spp_code,n_locations,scientific_name,american_english_name,taxonomy_version,taxonomic_sort_order
0,L100032,PFW_2002,0.0,0.0,1.0,1.0,0.0,1.0,NaN,NaN,...,1.0,1.001,0.000,PFW Web 4.1.4,NaN,85183,Junco hyemalis,Dark-eyed Junco,2022,32449
1,L100032,PFW_2002,0.0,0.0,1.0,1.0,0.0,1.0,NaN,NaN,...,1.0,1.001,0.001,PFW Web 4.0.4,NaN,40529,Zonotrichia albicollis,White-throated Sparrow,2022,32526
2,L100032,PFW_2002,0.0,0.0,1.0,1.0,0.0,1.0,NaN,NaN,...,1.0,1.001,5.000,PFW Web 4.1.4,NaN,73537,Cyanocitta cristata,Blue Jay,2022,20786
3,L100032,PFW_2002,0.0,0.0,1.0,1.0,0.0,1.0,NaN,NaN,...,1.0,1.001,0.000,PFW Web 4.1.4,NaN,73537,Cyanocitta cristata,Blue Jay,2022,20786
4,L100032,PFW_2002,0.0,0.0,1.0,1.0,0.0,1.0,NaN,NaN,...,1.0,1.001,15.001,PFW Web 4.1.4,NaN,73537,Cyanocitta cristata,Blue Jay,2022,20786

Paring down the data to a more manageable size

In [7]:
#couting species
# I want to know how many unique species are listed in the data. There are 360.
pfw['species_code'].nunique()

360

In [8]:
#I now want to see what the names of the species are in plain English. Since I merged the tables on the species code, I will look at 'species_code' and 'american_english_name'. 
pfw[['species_code', 'american_english_name']]

       species_code   american_english_name
0            daejun         Dark-eyed Junco
1            whtspa  White-throated Sparrow
2            blujay                Blue Jay
3            blujay                Blue Jay
4            blujay                Blue Jay
...             ...                     ...
504980       houspa           House Sparrow
504981       bkcchi  Black-capped Chickadee
504982       spotow          Spotted Towhee
504983      wooscj2   Woodhouse's Scrub-Jay
504984       houspa           House Sparrow

[504985 rows x 2 columns]

In [9]:
#counting number of unique species with American English names

species_uniq = pfw.groupby(['species_code', 'american_english_name']).nunique()
species_uniq

,,loc_id,proj_period_id,yard_type_pavement,yard_type_garden,yard_type_landsca,yard_type_woods,yard_type_desert,hab_dcid_woods,hab_evgr_woods,hab_mixed_woods,...,day2_am,day2_pm,effort_hrs_atleast,snow_dep_atleast,Data_Entry_Method,alt_full_spp_code,n_locations,scientific_name,taxonomy_version,taxonomic_sort_order
species_code,american_english_name,,,,,,,,,,,,,,,,,,,,,
abetow,Abert's Towhee,22,16,1,2,2,2,2,2,2,2,...,2,2,4,1,2,0,1,1,1,1
accipi,Accipiter sp.,7,9,1,1,2,2,2,2,2,2,...,2,2,3,2,1,0,1,1,1,1
acowoo,Acorn Woodpecker,50,21,2,2,2,2,1,2,2,2,...,2,2,4,2,2,0,1,1,1,1
allhum,Allen's Hummingbird,40,26,1,2,2,2,2,2,2,2,...,2,2,4,1,3,0,1,1,1,1
altori,Altamira Oriole,1,1,1,1,1,1,1,1,1,1,...,1,1,1,1,1,0,1,1,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
yerwar3,Yellow-rumped Warbler (Myrtle x Audubon's),1,3,1,1,1,1,1,1,1,1,...,1,1,1,0,1,1,1,1,1,1
yesfli,Northern Flicker (Yellow-shafted),9,9,1,1,2,2,1,2,2,2,...,1,2,2,2,3,1,1,1,1,1
yetvir,Yellow-throated Vireo,1,3,1,1,1,1,1,1,1,1,...,1,1,1,1,1,0,1,1,1,1
yetwar,Yellow-throated Warbler,18,29,1,2,2,2,1,2,2,2,...,2,2,4,1,3,0,1,1,1,1
zebdov,Zebra Dove,1,10,1,1,2,2,1,1,1,1,...,1,1,1,1,1,0,1,1,1,1

In [11]:
# I want to see how many of each species were sighted at each sighting (each row). 

#how many sighted of each species
species_count = pfw.groupby(['american_english_name', 'how_many']).agg(
    highest_sighting = ('how_many', 'max')

).sort_values(by='how_many', ascending=False)

species_count
## This was an alternate way to count them: pfw[['american_english_name', 'how_many']].sort_values(by=['how_many'],ascending=False)

## I tried it first with just sort_values() and then with groupby().sort_values() to check that 500 was correct. 
## Using .groupby(), I can see that there are only two species that have a sighting of 500 birds, which seems like too round of a number and very high. 
## I need to look for outliers and likely remove them from the data, since I am trying to find the average best feeder placement.

                                  highest_sighting
american_english_name   how_many
Lesser Scaup            500.0                500.0
Gray-crowned Rosy-Finch 500.0                500.0
Common Redpoll          250.0                250.0
Bohemian Waxwing        250.0                250.0
Evening Grosbeak        250.0                250.0
...                                            ...
Steller's Jay           1.0                    1.0
Sharp-shinned Hawk      1.0                    1.0
Short-eared Owl         1.0                    1.0
Snow Bunting            1.0                    1.0
American Crow           1.0                    1.0

[2401 rows x 1 columns]

In [12]:
# Since there are already clearly outliers, I want to make sure that all of the sighting data is accurate. 
# There is a 'reviewed' column that should indicate the review state of each observation based on the PFW flagging system.
# Of the 504985 rows, only 2038 have been reviewed. 
pfw['reviewed'].value_counts()

reviewed
0.0    502947
1.0      2038
Name: count, dtype: int64

In [13]:

# I also wanted to check the 'valid' column, which indicates whether the observation is considered valid by the PFW flagging system. 
# Sightings that are not valid cannot be verified as true and/or accurate, and so are not useful data. 
# Of the 504985 rows, 3674 are valid. 
pfw['valid'].value_counts()

valid
1.0    501311
0.0      3674
Name: count, dtype: int64

In [14]:
# I want to create a dataframe that has all of the rows and columns ONLY if 'valid' and 'reviewed' are True (1.0)

pfw_VR = pfw.loc[(pfw['valid']==1.0) & (pfw['reviewed']==1.0)]
pfw_VR

#Now the pfw_VR (validated and reviewed) dataframe has only entries that are confirmed by PFW to be true sightings. I will work with this data from here on.

,loc_id,proj_period_id,yard_type_pavement,yard_type_garden,yard_type_landsca,yard_type_woods,yard_type_desert,hab_dcid_woods,hab_evgr_woods,hab_mixed_woods,...,day2_pm,effort_hrs_atleast,snow_dep_atleast,Data_Entry_Method,alt_full_spp_code,n_locations,scientific_name,american_english_name,taxonomy_version,taxonomic_sort_order
562,L10022496,PFW_2020,0.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0,...,0.0,1.001,0.001,PFW Web 4.1.4,NaN,2782,Branta canadensis,Canada Goose,2022,319
574,L10022496,PFW_2021,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,...,0.0,1.001,0.001,PFW Web 4.1.4,NaN,2782,Branta canadensis,Canada Goose,2022,319
1115,L10049673,PFW_2020,0.0,0.0,0.0,1.0,0.0,1.0,0.0,1.0,...,1.0,1.001,NaN,PFW Web 4.1.4,NaN,71948,Cardinalis cardinalis,Northern Cardinal,2022,33811
1130,L10049673,PFW_2021,0.0,0.0,1.0,1.0,0.0,1.0,0.0,1.0,...,1.0,1.001,NaN,PFW Web 4.1.4,NaN,71948,Cardinalis cardinalis,Northern Cardinal,2022,33811
1515,L10076651,PFW_2020,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,...,1.0,1.001,0.000,PFW Web 4.1.4,NaN,78999,Zenaida macroura,Mourning Dove,2022,2405
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
504894,L99918,PFW_2017,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,...,1.0,1.001,0.000,PFW Web 4.1.4,NaN,2434,Pheucticus ludovicianus,Rose-breasted Grosbeak,2022,33853
504913,L99918,PFW_2018,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,...,1.0,1.001,0.000,PFW Web 4.1.4,NaN,2434,Pheucticus ludovicianus,Rose-breasted Grosbeak,2022,33853
504932,L99918,PFW_2019,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,...,1.0,1.001,0.000,PFW Web 4.1.4,NaN,2434,Pheucticus ludovicianus,Rose-breasted Grosbeak,2022,33853
504951,L99918,PFW_2020,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,...,1.0,1.001,0.000,PFW Web 4.1.4,NaN,2434,Pheucticus ludovicianus,Rose-breasted Grosbeak,2022,33853
504970,L99918,PFW_2021,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,...,1.0,1.001,0.000,PFW Web 4.1.4,NaN,2434,Pheucticus ludovicianus,Rose-breasted Grosbeak,2022,33853

In [ ]:
#I will also pare down the dataframe some more based on checkpoint 3, using .drop() and .query() to remove unnecessary rows from the 'pfw_species_codes_dict.csv' and data that are not from the year 2021. 
pfw_VR_2021 = pfw_VR.query('proj_period_id == "PFW_2021"')
pfw_VR_2021 = pfw_VR_2021.drop(columns=['alt_full_spp_code','n_locations', 'taxonomy_version', 'taxonomic_sort_order'])
pfw_VR_2021 = pfw_VR_2021.drop(columns=['subnational1_code', 'entry_technique', 'sub_id', 'obs_id', 'Data_Entry_Method'])
pfw_VR_2021
 #I can use this smaller dataset if I need a more specific slice of data from a smaller time frame. 
 # Otherwise, I can use the larger pfw_VR dataframe that has all of the dates but still only has the validated and reviewed rows.

,loc_id,proj_period_id,yard_type_pavement,yard_type_garden,yard_type_landsca,yard_type_woods,yard_type_desert,hab_dcid_woods,hab_evgr_woods,hab_mixed_woods,...,valid,reviewed,day1_am,day1_pm,day2_am,day2_pm,effort_hrs_atleast,snow_dep_atleast,scientific_name,american_english_name
574,L10022496,PFW_2021,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,...,1.0,1.0,0.0,1.0,1.0,0.0,1.001,0.001,Branta canadensis,Canada Goose
1130,L10049673,PFW_2021,0.0,0.0,1.0,1.0,0.0,1.0,0.0,1.0,...,1.0,1.0,1.0,1.0,1.0,1.0,1.001,NaN,Cardinalis cardinalis,Northern Cardinal
1529,L10076651,PFW_2021,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,...,1.0,1.0,1.0,1.0,1.0,1.0,1.001,0.000,Zenaida macroura,Mourning Dove
1733,L10090343,PFW_2021,0.0,0.0,1.0,1.0,0.0,0.0,0.0,1.0,...,1.0,1.0,1.0,1.0,1.0,1.0,1.001,0.000,Zonotrichia albicollis,White-throated Sparrow
3196,L10128133,PFW_2021,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,...,1.0,1.0,1.0,0.0,1.0,0.0,1.001,0.000,Meleagris gallopavo,Wild Turkey
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
493549,L8827693,PFW_2021,0.0,0.0,1.0,1.0,0.0,1.0,0.0,0.0,...,1.0,1.0,1.0,1.0,1.0,1.0,8.001,0.000,Dumetella carolinensis,Gray Catbird
495577,L8927802,PFW_2021,0.0,0.0,1.0,1.0,0.0,0.0,0.0,1.0,...,1.0,1.0,0.0,1.0,0.0,1.0,1.001,0.000,Pheucticus ludovicianus,Rose-breasted Grosbeak
497085,L97667,PFW_2021,0.0,0.0,1.0,1.0,0.0,0.0,0.0,1.0,...,1.0,1.0,1.0,1.0,1.0,1.0,4.001,0.000,Cyanocitta cristata,Blue Jay
503262,L991606,PFW_2021,0.0,0.0,1.0,1.0,0.0,0.0,0.0,1.0,...,1.0,1.0,1.0,1.0,1.0,1.0,1.001,0.000,Aix sponsa,Wood Duck
504970,L99918,PFW_2021,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,...,1.0,1.0,1.0,1.0,1.0,1.0,1.001,0.000,Pheucticus ludovicianus,Rose-breasted Grosbeak

In [17]:
pfw_VR.shape

# I will now explore more of the columns that describe the feeder locations, weather conditions, and predators.

(2035, 89)

In [ ]:
# I want to see how many unique bird types have been sighted and what are the most common. 

bird_agg_dict = {
    'how_many': 'sum',                # Summing the number of birds
    'species_code': 'nunique' # Count unique bird types 
}
most_common_bird_types = pfw_VR.groupby('american_english_name').agg(
    bird_agg_dict
).sort_values(by='how_many', ascending=False)

most_common_bird_types.head(50)

#The top 50 most common birds interestingly have few entries for very common birds such as the American Robin and the Gray Catbird. 
# This is possibly due to these birds not being recorded since they are so common (my opion).

                              how_many  species_code
american_english_name
Pine Siskin                     7103.0             1
Common Redpoll                  3955.0             1
American Goldfinch              3390.0             1
Blue Jay                        2932.0             1
Northern Cardinal               2720.0             1
Purple Finch                    2486.0             1
Mourning Dove                   2258.0             1
Black-bellied Whistling-Duck    2145.0             1
Evening Grosbeak                1338.0             1
Canada Goose                    1261.0             1
White-throated Sparrow          1255.0             1
Red-winged Blackbird            1059.0             1
House Sparrow                    805.0             1
Anna's Hummingbird               706.0             1
Eurasian Collared-Dove           652.0             1
House Finch                      608.0             1
Lesser Goldfinch                 600.0             1
Common Raven                     540.0             1
Rock Pigeon (Feral Pigeon)       540.0             1
Wild Turkey                      476.0             1
Brown-headed Cowbird             364.0             1
Painted Bunting                  359.0             1
Steller's Jay                    297.0             1
European Starling                283.0             1
Mallard (Domestic type)          256.0             1
American Tree Sparrow            252.0             1
Sandhill Crane                   232.0             1
Wood Duck                        208.0             1
Mallard                          171.0             1
White-winged Crossbill           157.0             1
Canada Jay                       143.0             1
Dark-eyed Junco                  130.0             1
Northern Flicker                 128.0             1
Orange-crowned Warbler           128.0             1
Trumpeter/Tundra Swan            114.0             1
Yellow-rumped Warbler            110.0             1
rosy-finch sp.                   100.0             1
Blue-winged Teal                  96.0             1
Black-headed Grosbeak             86.0             1
Eastern Bluebird                  84.0             1
Red-bellied Woodpecker            78.0             1
Rose-breasted Grosbeak            76.0             1
Gray Catbird                      72.0             1
Muscovy Duck                      71.0             1
Allen's Hummingbird               68.0             1
Indigo Bunting                    63.0             1
Red-whiskered Bulbul              50.0             1
Western Bluebird                  44.0             1
Ruby-throated Hummingbird         38.0             1
American Robin                    38.0             1

In [32]:
# I want to see what type of birds used each type of feeder. I will start with the suet feeder, summing the unique birds and how many came to suet feeders, as well as how many feeders. 

suet_agg_dict = {
    'how_many': 'count',                # Summing the number of birds using the suet feeder
    'numfeeders_suet': 'count',         # Counting the number of suet
    'species_code': 'nunique' # unique bird types 
}

suet_feeder_bird_types = pfw_VR.groupby('american_english_name').agg(
    suet_agg_dict
).sort_values(by='numfeeders_suet', ascending=False)

suet_feeder_bird_types.head(25)

#I think what this output is telling me is that 241/243 sightings of pine siskins were using suet feeders, 142/147 sightings of blue jays were using suet feeders, etc.

                         how_many  numfeeders_suet  species_code
american_english_name
Pine Siskin                   243              241             1
Blue Jay                      147              142             1
Northern Cardinal              94               89             1
Anna's Hummingbird             89               89             1
Eurasian Collared-Dove        108               68             1
Mallard (Domestic type)        62               62             1
White-throated Sparrow         58               56             1
Wood Duck                      56               56             1
Purple Finch                   56               55             1
American Goldfinch             54               51             1
Mourning Dove                  52               43             1
Red-winged Blackbird           43               43             1
Gray Catbird                   40               40             1
Painted Bunting                39               38             1
Rose-breasted Grosbeak         38               38             1
Wild Turkey                    37               37             1
Yellow-throated Warbler        33               33             1
Orange-crowned Warbler         34               30             1
Lesser Goldfinch               31               30             1
White-winged Crossbill         29               29             1
Red-bellied Woodpecker         28               28             1
Black-headed Grosbeak          30               28             1
Indigo Bunting                 29               27             1
Canada Goose                   29               26             1
Baltimore Oriole               24               24             1

In [ ]:
ground_agg_dict = {
    'how_many': 'count',                # Summing the number of birds using the ground feeder
    'numfeeders_ground': 'count',         # Counting the number of ground feeders
    'species_code': 'nunique', # unique bird types 
}

ground_feeder_bird_types = pfw_VR.groupby('american_english_name').agg(
    ground_agg_dict
).sort_values(by='numfeeders_ground', ascending=False)

ground_feeder_bird_types.head(25)

# The ground feeders have similar results to the suet feeders, attracting pine siskins, blue jays, and northern cardinals as the top 3 species.

                          how_many  numfeeders_ground  species_code
american_english_name
Pine Siskin                    243                225             1
Blue Jay                       147                130             1
Northern Cardinal               94                 89             1
Anna's Hummingbird              89                 88             1
Eurasian Collared-Dove         108                 68             1
Mallard (Domestic type)         62                 58             1
Wood Duck                       56                 54             1
White-throated Sparrow          58                 53             1
Purple Finch                    56                 50             1
Mourning Dove                   52                 48             1
Red-winged Blackbird            43                 43             1
Gray Catbird                    40                 40             1
Wild Turkey                     37                 36             1
Rose-breasted Grosbeak          38                 35             1
Orange-crowned Warbler          34                 34             1
American Goldfinch              54                 31             1
Painted Bunting                 39                 31             1
Great Crested Flycatcher        31                 29             1
Lesser Goldfinch                31                 28             1
Red-bellied Woodpecker          28                 28             1
Yellow-throated Warbler         33                 27             1
Indigo Bunting                  29                 27             1
White-winged Crossbill          29                 25             1
Canada Goose                    29                 25             1
Black-headed Grosbeak           30                 21             1

In [ ]:
# I want to see the impact of habitat on the different species as well. 
# I am going to look at ground feeders in deciduous woods to see what the results are. 

dcid_woods_agg_dict = {
    'how_many': 'count',                # Summing the number of birds using the ground feeder
    'numfeeders_ground': 'count',         # Counting the number of ground feeders
    'hab_dcid'
    'species_code': 'nunique', # unique bird types 
}

ground_feeder_bird_types = pfw_VR.groupby('american_english_name').agg(
    ground_agg_dict
).sort_values(by='numfeeders_ground', ascending=False)

ground_feeder_bird_types.head(25)

## Visualize

Create any visualizations for your EDA here. Make note in the form of code comments of what your thought process is for your visualizations.

In [ ]:
import matplotlib.pyplot as plt

Getting a sense for outliers

In [ ]:
#I will use a box and whisker plot to get a sense of outlier sightings that have a very large number of birds. 

x = [pfw_VR['how_many']]

plt.boxplot(x)

Exploring the feeder conditions

In [ ]:
# I wanted to determine which feeders were the most popular to use, and therefore would be the most useful for my data.
# Since hanging, water, and thistle feeders have very few uses, I am going to remove them from the rest of my analysis. 
print(pfw_VR['numfeeders_suet'].isna().value_counts(),
      pfw_VR['numfeeders_ground'].isna().value_counts(),
      pfw_VR['numfeeders_hanging'].isna().value_counts(),
      pfw_VR['numfeeders_platfrm'].isna().value_counts(),
      pfw_VR['numfeeders_humming'].isna().value_counts(),
      pfw_VR['numfeeders_water'].isna().value_counts(),
      pfw_VR['numfeeders_thistle'].isna().value_counts(),
      pfw_VR['numfeeders_fruit'].isna().value_counts(),
      pfw_VR['numfeeders_hopper'].isna().value_counts(),
      pfw_VR['numfeeders_tube'].isna().value_counts(),
      pfw_VR['numfeeders_other'].isna().value_counts()
      )

columns = ['numfeeders_suet', 
           'numfeeders_ground', 
           'numfeeders_hanging', 
        'numfeeders_platfrm', 
        'numfeeders_humming', 
        'numfeeders_water', 
        'numfeeders_thistle', 
        'numfeeders_fruit', 
        'numfeeders_hopper', 
        'numfeeders_tube', 
        'numfeeders_other']

num_of_feeders = {}

for col in columns:
    num_of_feeders[col] = (~pfw_VR[col].isna()).sum()

num_of_feeders_series = pd.Series(num_of_feeders)

plt.figure(figsize=(10,6))
num_of_feeders_series.plot(kind='bar', color='orange')
plt.title('Count of Types of Feeders')
plt.xlabel('Feeder Type')
plt.ylabel('Number of Entries')
plt.xticks(rotation=45, ha='right')
plt.tight_layout()
plt.show()

In [ ]:
#I will do a similar check on the types of habitats and other variables to get the most complete data for my analysis. 
columns = [
    'hab_dcid_woods', 
    'hab_evgr_woods',
    'hab_mixed_woods',
    'hab_orchard', 
    'hab_park', 
    'hab_water_fresh', 
    'hab_water_salt', 
    'hab_residential', 
    'hab_industrial', 
    'hab_agricultural',
    'hab_desert_scrub', 
    'hab_young_woods', 
    'hab_swamp', 
    'hab_marsh'
]

type_of_habitat = {}

for col in columns:
    type_of_habitat[col] = (~pfw_VR[col].isna()).sum()

type_of_habitat_series = pd.Series(type_of_habitat)

plt.figure(figsize=(10,6))
type_of_habitat_series.plot(kind='bar', color='skyblue')
plt.title('Count of Types of Habitats')
plt.xlabel('Habitat Type')
plt.ylabel('Number of Entries')
plt.xticks(rotation=45, ha='right')
plt.tight_layout()
plt.show()

# There is a fairly even spread of entries for each type of habitat. I will likely need to choose a different variable if I want to pare down the data. 
# Or, the many types of habitat could provide interesting comparisons.

In [ ]:
# Visualizing the yard types

columns = [
    'yard_type_pavement', 
    'yard_type_garden', 
    'yard_type_landsca', 
    'yard_type_woods', 
    'yard_type_desert'
]

type_of_yard = {}

for col in columns:
    type_of_yard[col] = (~pfw_VR[col].isna()).sum()

type_of_yard_series = pd.Series(type_of_yard)

plt.figure(figsize=(10,6))
type_of_yard_series.plot(kind='bar', color='lightgreen')
plt.title('Count of Types of Yards')
plt.xlabel('Yard Type')
plt.ylabel('Number of Entries')
plt.xticks(rotation=45, ha='right')
plt.tight_layout()
plt.show()

# There is again a fairly even spread of different yard types.

In [ ]:
#counting yard types
print(pfw['yard_type_pavement'].value_counts(),
pfw['yard_type_garden'].value_counts(),
pfw['yard_type_landsca'].value_counts(),
pfw['yard_type_woods'].value_counts(),
pfw['yard_type_desert'].value_counts())

In [ ]:
#exploring feeder types
most_popular_feeder = pfw_VR.groupby(by=['how_many']).agg(
    suet_total = ('numfeeders_suet', 'sum'),
    ground_total = ('numfeeders_ground', 'sum'),
    hanging_total = ('numfeeders_hanging', 'sum'),
    platform_total = ('numfeeders_platfrm', 'sum'),
    hummingbird_total = ('numfeeders_humming', 'sum'),
    water_total = ('numfeeders_water', 'sum'),
    thistle_total = ('numfeeders_thistle', 'sum'),
    fruit_total = ('numfeeders_fruit', 'sum'),
    hopper_total = ('numfeeders_hopper', 'sum'),
    tube_total = ('numfeeders_tube', 'sum'),
    other_total = ('numfeeders_other', 'sum')
).sort_values(by=['how_many'],ascending=False)

most_popular_feeder
#not sure if this is showing what I want it to. I want to see how many feeders it takes to get the most birds?

## Summarize Your Results

With your EDA complete, answer the following questions.

1. Was there anything surprising about your dataset? 
2. Do you have any concerns about your dataset? 
3. Is there anything you want to make note of for the next phase of your analysis, which is cleaning data?